name: Hprofile-Actions
on: workflow_dispatch
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      
      - name: Maven test
        run: mvn test
      
      - name: checkstyle
        run: mvn checkstyle:checkstyle

      # Setup java 17 to be default (sonar-scanner requirement)
      - name: Set Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      # Setup sonnar-scanner
      - name: Setup sonnarQube
        uses: warchant/setup-sonar-scanner@v7
      
      # Run sonar-scanner
      - name: Sonarqube Scan
        run: sonar-scanner
          -Dsonar.host.url=${{ secrets.HOST }}
          -Dsonar.login=${{ secrets.LOGIN }}
          -Dsonar.organization=${{ secrets.ORGANIZATION }}
          -Dsonar.projectKey=${{ secrets.PROJECT }}
          -Dsonar.sources=src/
          -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/
          -Dsonar.junit.reportsPath=target/surefire-reports/
          -Dsonar.jacoco.reportsPath=target/jacoco.exec
          -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml
